# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNLenddoEFLSdkWrapperDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNLenddoEFLSdkWrapperDemo
  pod 'GoogleSignIn'

  target 'RNLenddoEFLSdkWrapperDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNLenddoEFLSdkWrapperDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNLenddoEFLSdkWrapperDemo-tvOS

  target 'RNLenddoEFLSdkWrapperDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
